"""initial schema

Revision ID: e6483167eca5
Revises: 
Create Date: 2026-09-20 13:55:01.377719
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e6483167eca5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tracking_frequency', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_name'), ['name'], unique=True)

    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('raw_changes', sa.Integer(), nullable=False),
    sa.Column('noise_changes', sa.Integer(), nullable=False),
    sa.Column('meaningful_changes', sa.Integer(), nullable=False),
    sa.Column('high_impact_changes', sa.Integer(), nullable=False),
    sa.Column('noise_reduction', sa.Float(), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digests_created_at'), ['created_at'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('snapshot_a', sa.String(length=40), nullable=True),
    sa.Column('snapshot_b', sa.String(length=40), nullable=True),
    sa.Column('pages_evaluated', sa.Integer(), nullable=False),
    sa.Column('raw_changes', sa.Integer(), nullable=False),
    sa.Column('noise_changes', sa.Integer(), nullable=False),
    sa.Column('meaningful_changes', sa.Integer(), nullable=False),
    sa.Column('high_impact_changes', sa.Integer(), nullable=False),
    sa.Column('noise_reduction', sa.Float(), nullable=False),
    sa.Column('category_breakdown', sa.Text(), nullable=False),
    sa.Column('report_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_created_at'), ['created_at'], unique=False)

    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('urls_scanned', sa.Integer(), nullable=False),
    sa.Column('urls_failed', sa.Integer(), nullable=False),
    sa.Column('raw_changes', sa.Integer(), nullable=False),
    sa.Column('noise_changes', sa.Integer(), nullable=False),
    sa.Column('meaningful_changes', sa.Integer(), nullable=False),
    sa.Column('high_impact_changes', sa.Integer(), nullable=False),
    sa.Column('noise_reduction', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_runs_competitor_id'), ['competitor_id'], unique=False)

    op.create_table('tracked_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('page_type', sa.String(length=40), nullable=False),
    sa.Column('render_js', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=40), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'url', name='uq_tracked_url_per_competitor')
    )
    with op.batch_alter_table('tracked_urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_urls_competitor_id'), ['competitor_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_url_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_html_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_url_id'], ['tracked_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_url_time', ['tracked_url_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_tracked_url_id'), ['tracked_url_id'], unique=False)

    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('is_noise', sa.Boolean(), nullable=False),
    sa.Column('noise_reason', sa.String(length=200), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('classifier_confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.create_index('ix_change_noise_score', ['is_noise', 'relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_is_noise'), ['is_noise'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analysed_by', sa.String(length=40), nullable=False),
    sa.Column('llm_status', sa.String(length=20), nullable=False),
    sa.Column('llm_error', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('tracked_url_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('previous_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracked_url_id'], ['tracked_urls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intelligence_change_id'), ['change_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_intelligence_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_tracked_url_id'), ['tracked_url_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_tracked_url_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_created_at'))
        batch_op.drop_index(batch_op.f('ix_intelligence_competitor_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_change_id'))

    op.drop_table('intelligence')
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changes_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_changes_is_noise'))
        batch_op.drop_index(batch_op.f('ix_changes_detected_at'))
        batch_op.drop_index(batch_op.f('ix_changes_competitor_id'))
        batch_op.drop_index('ix_change_noise_score')

    op.drop_table('changes')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_tracked_url_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_snapshots_content_hash'))
        batch_op.drop_index(batch_op.f('ix_snapshots_competitor_id'))
        batch_op.drop_index('ix_snapshot_url_time')

    op.drop_table('snapshots')
    with op.batch_alter_table('tracked_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_urls_competitor_id'))

    op.drop_table('tracked_urls')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_runs_competitor_id'))

    op.drop_table('scan_runs')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_created_at'))

    op.drop_table('evaluations')
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digests_created_at'))

    op.drop_table('digests')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_name'))

    op.drop_table('competitors')
    # ### end Alembic commands ###
