"use client";

import { useState } from "react";

import { Figure } from "@/components/Metrics";
import { Reveal } from "@/components/Reveal";
import { DigestSkeleton } from "@/components/Skeletons";
import {
  Button,
  EmptyState,
  ErrorState,
  PageHeader,
  SectionTitle,
} from "@/components/ui";
import { useAction, useApi } from "@/hooks/useApi";
import { api } from "@/lib/api";
import { formatDate, formatNumber, formatPercent } from "@/lib/format";
import type { Digest } from "@/lib/types";

/**
 * Weekly digest.
 *
 * A research briefing: masthead, measured statistics, the executive summary
 * set large, then the report itself.
 *
 * The report body is authored as plain text by the backend and uses column
 * alignment, so it is rendered verbatim in the mono face. Reflowing it into
 * proportional type would break its alignment and risk misrepresenting it.
 */
export default function DigestPage() {
  const digest = useApi(() => api.getLatestDigest(), []);
  const generate = useAction(api.generateDigest);
  const [days, setDays] = useState(7);

  const notGenerated = digest.error?.toLowerCase().includes("no digest");

  async function handleGenerate() {
    if (await generate.run(days)) digest.refetch();
  }

  return (
    <div className="animate-page">
      <PageHeader
        title="Weekly competitive digest"
        description="A period summary assembled from stored intelligence records, with the measured funnel attached."
        action={
          <>
            <select
              value={days}
              onChange={(event) => setDays(Number(event.target.value))}
              className="input w-auto"
              aria-label="Digest period"
            >
              <option value={7}>Last 7 days</option>
              <option value={14}>Last 14 days</option>
              <option value={30}>Last 30 days</option>
            </select>
            <Button onClick={handleGenerate} disabled={generate.pending}>
              {generate.pending ? "Generating…" : "Generate"}
            </Button>
          </>
        }
      />

      {generate.error && (
        <div className="mt-10">
          <ErrorState message={generate.error} compact />
        </div>
      )}

      <div className="mt-12">
      {digest.loading && !digest.data ? (
        <DigestSkeleton />
      ) : notGenerated ? (
        <EmptyState
          title="No digest generated yet"
          description="Generate a briefing to summarise the competitive movements detected in the selected period."
          action={
            <Button onClick={handleGenerate} disabled={generate.pending}>
              {generate.pending ? "Generating…" : "Generate the first digest"}
            </Button>
          }
        />
      ) : digest.error ? (
        <ErrorState
          title="Cannot load the digest"
          message={digest.error}
          onRetry={digest.refetch}
        />
      ) : digest.data ? (
        <DigestReport digest={digest.data} />
      ) : null}
      </div>
    </div>
  );
}

function DigestReport({ digest }: { digest: Digest }) {
  return (
    <article>
      <p className="text-[13px] text-[var(--ink-soft)]">
        {formatDate(digest.period_start)} &ndash; {formatDate(digest.period_end)}
      </p>

      <div className="mt-6 grid grid-cols-2 gap-x-8 gap-y-6 border-y border-[var(--line)] py-6 sm:grid-cols-5">
        <Figure label="Raw" value={formatNumber(digest.raw_changes)} />
        <Figure label="Noise" value={formatNumber(digest.noise_changes)} />
        <Figure label="Meaningful" value={formatNumber(digest.meaningful_changes)} />
        <Figure
          label="High impact"
          value={formatNumber(digest.high_impact_changes)}
          accent={digest.high_impact_changes > 0 ? "var(--critical)" : undefined}
        />
        <Figure label="Noise removed" value={formatPercent(digest.noise_reduction)} />
      </div>

      {digest.headline && (
        <Reveal as="section" className="mt-16">
          <SectionTitle title="Executive summary" />
          <p className="max-w-[58ch] text-[19px] font-medium leading-[1.45] tracking-[-0.015em]">
            {digest.headline}
          </p>
        </Reveal>
      )}

      <Reveal as="section" className="mt-16">
        <SectionTitle
          title="Report"
          action={
            <span className="text-[11.5px] text-[var(--ink-faint)]">
              Generated by <span className="mono">{digest.generated_by}</span>
            </span>
          }
        />
        <pre className="overflow-x-auto whitespace-pre-wrap border-t border-[var(--line)] pt-6 font-[family-name:var(--font-mono)] text-[12.5px] leading-[1.8] text-[var(--ink-soft)]">
          {digest.content}
        </pre>
      </Reveal>
    </article>
  );
}
